### ISSUE TITLE
Using TCP transport instead of UDP

### ISSUE THREAD

**Issue by alishir** [juha-h/baresip-studio#10]
Hi @juha-h,

Thanks for your great effort. I just installed baresip-studio on an android device, I want to change transmit protocol from UDP to TCP, but I didn't find anything in config and account menu.
So is it possible to change transmit protocol from UI? if it is not would you please guide me how to add this feature to baresip-studio?

Regards,
Ali

**Comment by juha-h** [comment]
Ali Shirvani writes:

> Thanks for your great effort. I just installed baresip-studio on an
> android device, I want to change transmit protocol from UDP to TCP,
> but I didn't find anything in config and account menu.
> So is it possible to change transmit protocol from UI? if it is not
> would you please guide me how to add this feature to baresip-studio?

Sure it is.  Go to Account page and click Outbound Proxies heading for
help.

-- Juha

**Comment by alishir** [comment]
Thanks, but how if I try to connect to the sip server without outbound proxy, in `baresip` we can define users like: `<sip:ali@127.0.0.1:5060;transport=tcp>` but in the `baresip-studio` I coudn't use this type of URI.

**Comment by alishir** [comment]
Thanks for your detailed answer. But the following scenario doesn't work:
- Opening accounts view
- Trying ali@192.168.5.34:5060 as SIP URI cause `Invalid SIPAddress of Record`
- Trying ali@192.168.5.34;transport=tcp as SIP URI cause `Invalid SIPAddress of Record`
- Trying ali@192.168.5.34 works fine.
- I checked Register checkbox

But I get REGISTER request on the UDP and I want to receive REGISTER request on TCP, also I have no outbond proxy, my SIP server is listening on 192.168.5.34 port 5060 tcp.

How can I set the application to send REGISTER request over tcp port without using outbound proxy?
I can do this in zoiper without setting outbound proxy.

**Comment by juha-h** [comment]
Ali Shirvani writes:

> Thanks for your detailed answer. But the following scenario doesn't work:
> - Opening accounts view
> - Trying ali@192.168.5.34:5060 as SIP URI cause `Invalid SIPAddress of Record`
> - Trying ali@192.168.5.34;transport=tcp as SIP URI cause `Invalid SIPAddress of Record`
> - Trying ali@192.168.5.34 works fine.
> - I checked Register checkbox

You get the error message, because ali@192.168.5.34:5060 is not SIP
AoR.

> But I get REGISTER request on the UDP and I want to receive REGISTER
> request on TCP, also I have no outbond proxy, my SIP server is
> listening on 192.168.5.34 port 5060 tcp.
> 
> How can I set the application to send REGISTER request over tcp port
> without using outbound proxy? 
> I can do this in zoiper without setting outbound proxy.

Use domain name instead of IP address in your AoR and set the DNS
(NAPTR/SRV) record(s) that tell to use tcp.  Or define Outbound Proxy.

**Comment by juha-h** [comment]
From RFC 3261:

10.2 Constructing the REGISTER Request
,,,
   The following header fields, except Contact, MUST be included in a
   REGISTER request.  A Contact header field MAY be included:

      Request-URI: The Request-URI names the domain of the location
           service for which the registration is meant (for example,
           "sip:chicago.com").  The "userinfo" and "@" components of the
           SIP URI MUST NOT be present.

10.2.6 Discovering a Registrar

   UAs can use three ways to determine the address to which to send
   registrations:  by configuration, using the address-of-record, and
   multicast.  A UA can be configured, in ways beyond the scope of this
   specification, with a registrar address.  If there is no configured
   registrar address, the UA SHOULD use the host part of the address-
   of-record as the Request-URI and address the request there, using the
   normal SIP server location mechanisms [4].  For example, the UA for
   the user "sip:carol@chicago.com" addresses the REGISTER request to
   "sip:chicago.com".

There is currently no account configuration option to tell where to send
registrations.  I don't have plans to add one, since it is a very
special case if Outbound Proxy cannot for some reason used or DNS
properly configured.

**Comment by alishir** [comment]
Thanks a lot for the detailed explanation. So I close this issue.
