### ISSUE TITLE
Support editing the SIP server of an account

### ISSUE THREAD

**Issue by Ernest0x** [juha-h/baresip-studio#130]
For an account, one can change the authentication username, but cannot change the SIP server. For example, a "username1@sip1.mysipservice.org" account can be changed to "username2@sip1.mysipservice.org" but cannot be changed to "username1@sip2.mysipservice.org". The only way to do this is to delete the account and make a new one with the new SIP server, but you have to set all configuration options from the beginning, which is not practical.

**Comment by juha-h** [comment]
Your issue is not about changing SIP server, but changing domain part of your account's Address of Record (AoR).  SIP server of an account can be changed by changing Outbound Proxy, but changing AoR means deleting an account and creating a new one. What you ask is the same as asking to change your gmail email address without creating a new one. Sorry, that is not supported.

**Comment by Ernest0x** [comment]
Ok.
