### ISSUE TITLE
Non-working inbound calls with 29.2.1

### ISSUE THREAD

**Issue by robert-scheck** [juha-h/baresip-studio#152]
I'm using baresip 1.0.0 on RHEL/CentOS 7 and there it works perfectly fine with this simple configuration in `~/.baresip/accounts`:

```
<sip:sip123456@sip.example.net>;auth_pass=<password>;stunserver=stun:stun1.example.net:3478
```

I would have expected that the following (same?) configuration works using the baresip 29.2.1 app on Android 9 the same way:

  * Account: `sip:sip123456@sip.example.net`
  * Authentication Username: `sip123456`
  * Authentication Password: `<password>`
  * Register: ☑
  * Media NAT Traversal: `STUN`
  * STUN/TURN Server: `stun:stun1.example.net:3478`

Unfortunately, inbound calls to the baresip app are not working (the app simply never rings, but I afterwards see a missed call inside the baresip app). The SIP provider saw the following in their server debug logs while being connected using the baresip app:

```
sip:sip123456-0x74bcf45b50@192.168.0.42:42451;transport=tcp
```

The SIP provider claimed that `192.168.0.42` looks strange and makes them assuming that the STUN is not properly used on client side (= app), leading to a non-working NAT traversal (that's indeed my RFC 1918 address). Unfortunately the SIP provider is IPv4-only, so I can't avoid NAT (independent of WiFi and 4G).

First of all: Did I logically transfer the settings from the regular baresip to the app correctly?

**Comment by juha-h** [comment]
Your configuration seems to be OK.  Check with `logcat | grep Baresip', it you get something like this when you restart the app and your account is registered:
```
04-21 17:08:50.097 12022 12049 D Baresip Lib: using stunserver: 'stun:stun.l.google.com:19302'
04-21 17:08:50.097 12022 12049 D Baresip Lib: bar@example.com: Using medianat 'stun'
```
If you do, then STUN should be active.

**Comment by juha-h** [comment]
Is your  RHEL/CentOS 7 host connected to Internet the same way as your Android device?  For example, are they both connected to the same WiFi hotspot and thus behind the same NAT?

**Comment by robert-scheck** [comment]
Once it comes to WiFi, yes - same subnet, same access point etc.. 4G is smartphone-only indeed (but for testing I also explicitly turned off any data connections except WiFi).

**Comment by juha-h** [comment]
I tried with ;medianat=stun;stunserver="stun:stun.1und1.de:3478" in my Debian Linux baresip and wireshark didn't show any packets going to port 3478.  As I mentioned, I have never used STUN myself, because my Kamailio SIP Proxy/Registrar automatically learns my public IP address.

After enabling Debug in Settings, you could check with `adb logcat | grep Baresip' if anything happens when a call comes in.

**Comment by juha-h** [comment]
I did more testing and it turned out that baresip (cli or Android) does not appear to support STUN for SIP, but only for SDP media.  That is, IP address in Contact header will always have local IP address if the device is behind NAT. In order to confirm this, can you check with ngrep or wireshark, how does the Contact header look like, when you register your RHEL/CentOS 7 baresip?

You should ask your SIP provider to support SIP User Agents that are behind NAT.  In Kamailio SIP Proxy this is very easy to do.  If Contact header has local IP address, this function is called when REGISTER request is received: [http://www.kamailio.org/docs/modules/5.5.x/modules/nathelper.html#nathelper.f.fix_nated_register](url).  Then when call needs to be forwarded to this UA, SIP Proxy uses the "received" address.

**Comment by juha-h** [comment]
STUN support in baresip (Linux and Android) is only for media.  If you define an Outbound Proxy for your account with TCP or TLS transport, registration will use that and your SIP provider should use the same TCP or TLS connection to send requests to you.  Thus STUN for SIP is not needed.  If your SIP provider does not support TCP or TLS transport, then they need to be able to detect the public IP address and  UDP port where REGISTER request came from and use that to send requests to you.

**Comment by juha-h** [comment]
I'll close this due to lack of further information. As I have mentioned, baresip (CLI or Android version) does not use STUN for SIP.
