### ISSUE TITLE
Contacts from android native contact list

### ISSUE THREAD

**Issue by rabongithub** [juha-h/baresip-studio#190]
how to get the Contacts from android native contact list to your app ?

**Comment by sushidave** [comment]
Hei @juha-h, thank you for sharing this app with the public.

Thanks to your comment I realised that it's possible to make baresip calls from the contact app. 

The pre-installed app on my phone doesn't support SIP - I guess for privacy reasons since it's an OS without any Google services. By tapping a phone number in the contact app and selecting baresip the address is inserted in this format: 
`sip:+123 4 567 890@sip:username@sip.provider.xyz:5060`

A workaround is to copy and paste a number from the contact app into the Callee field of baresip which results in:
`+123 4 567 890`

This leads to the error message:
```
Notice
Invalid SIP URI 'sip:+123 4 567 890'
```
I assume it's due to the blanks because it works after deleting them (+1234567890).

Would it be useful to have baresip programmatically ignore such blanks in the Callee field? This would not only solve the copy+paste issue but also also cover such common cases where users type in phone numbers with blanks. What are your thoughts on this?

**Comment by juha-h** [comment]
This should now be fixed in https://github.com/juha-h/baresip-studio/commit/40f3990e5bc1069a4791e7ef1b7d5050ab1b457f.

**Comment by sushidave** [comment]
@juha-h Woah, thanks a lot :)
