### ISSUE TITLE
Battery draining

### ISSUE THREAD

**Issue by Saphar** [juha-h/baresip-studio#198]
I noticed the battery draining more since I have baresip installed. Is there a way to improve this?

**Comment by Saphar** [comment]
I found it duplicate. Sorry. I will read first the other issue

**Comment by juha-h** [comment]
Saphar writes:

> I noticed the battery draining more since I have baresip installed. Is
> there a way to improve this?

There is no way to make baresip not to consume battery, since it needs
to be able to receive calls at any time.  See Battery Optimizations
Setting and page

https://github.com/juha-h/baresip-studio/wiki/Battery-Consumption

If you don't mind Google being aware of calls you receive, choose some
other VoIP app that uses push notifications.

**Comment by Saphar** [comment]
Can this Battery Optimization be enabled in the config file? 

I would stick with baresip.

**Comment by juha-h** [comment]
Saphar writes:

> Can this Battery Optimization be enabled in the config file?

No, Google does not allow it.  It is enabled by default and you can
disable it by un-checking the Settings box, which leads to Android
settings.

**Comment by Saphar** [comment]
I did some debugging and what I noticed is that I am using OpenVPN and if I have the network disabled it still recognizes the network. Probably some settings that are left from the VPN. Maybe this makes it drain more that it thinks it has network, but it doesn't. I still need to do some more tests.
