### ISSUE TITLE
Add support for Unified Push

### ISSUE THREAD

**Issue by gdt** [juha-h/baresip-studio#199]
(I certainly agree with avoiding Google's push implementation.)

While people have been talking about non-google push for a long time, it's really starting to happen now.   Unified Push is an architecture and gotify is one implementation (that can be self hosted).   NextPush is another (for nextcloud).   At least some matrix clients work with it.

https://unifiedpush.org/

Obviously SIP servers will need to do the server half, but with that, then someone's phone could share one push connection across chat and SIP, and eventually more, mitigating the battery issue.

I realize that this would cause some implementatation complexity and that you might not want this, even with a PR (that honestly, I am highly unlikely to provide soon).

**Comment by juha-h** [comment]
Greg Troxel writes:

> While people have been talking about non-google push for a long time,
> it's really starting to happen now.   Unified Push is an architecture
> and gotify is one implementation (that can be self hosted).   NextPush
> is another (for nextcloud).   At least some matrix clients work with
> it.

Then user would need to be running a Unified Push app in as always on
foreground service w/o battery optimization that would consume about the
same amount of power as baresip, right?

If so, it would only make sense if user has several apps that are using
Unified Push.

**Comment by gdt** [comment]
That's right.

Indeed, it is equivalent in battery but more complicated if there is only 1, and a win at 2, and an increasing win for more.   This is really the exact same situation as FCM, except we're already in a place where apps support that (but of course no apps in f-droid).   The matrix and fediverse worlds are moving to UP, and I think the nextcloud client will use them.   So I expect more things in the free software world to support it over the next year. 

In my case, I'm already running Fedilab with UP, and expect to use a UP-capable matrix client soonish.

**Comment by juha-h** [comment]
I'm using Kamailio SIP Proxy and currently it does not include a push
notification module.  Many years ago there was an effort, but for some
reason the module was not included in Kamailio:

https://github.com/tvntsr/push

SIP UA needs to register at fixed intervals and there push notifications
do not help in reducing power consumption.

There may be various complications too, for example, when SIP Proxy
parallel forks an INVITE to several UAs and then cancels all except the
the one that responded.

In my tests where baresip with two registering accounts is running on
otherwise idle device, the device looses about %1 of battery power per
100 minutes of uptime, which I personally don't consider too much.

**Comment by gdt** [comment]
Agreed that the drain isn't that bad, but with N programs, it's going to depend on how important it is.  I have k-9 and Conversations as always-connected, and those both matter to me.

But, I think you're saying that if you did implement UP in both baresip and Kamailo, then only part of that 1% would be saved because there'd still need to be periodici registration, perhaps at fairly long intervals.

So if you feel like closing this as tracker noise, given that nobody is likely to write the code soon, I won't be offended at all.   (If there were a mailinglist I would have used that.)   Thanks for the discussion and taking the time to consider.

**Comment by juha-h** [comment]
Thanks for the discussion.  I'll consider adding Unified Push support if it becomes available in Kamailio so that I have platform to test it.

**Comment by codyit** [comment]
Here's another reason to support UnifiedPush, it handles CGNAT which is becoming the reality for my many carriers, without the need to understand the NAT method for each (particularly painful when traveling) nor the need to maintain extra proxy infra. The only requirement is for the server to support https://www.rfc-editor.org/rfc/rfc8599

Please bear with me as I've only been familiarizing myself with SIP and complex NAT recently to scratch my own itch, so I might confuse some terminologies. Here's the low cost no infra setup I'm trying to make work for my own single number.
* Twilio SIP
* Twilio serverless function (POC gist: https://gist.github.com/codyit/850a77373cfaa57492a4b38e6350bb39)
* Any android SIP agent 

I'm having similar issue in https://github.com/juha-h/baresip-studio/issues/128 where I can only receive calls less than ~120s after registration. For a successful call, from adb logcat / shell netstat I can see the INVITE is coming to the rport inside via instead of the contact port in AOR which looks like this `sip:someUser@10.2.0.2:40303;transport=tls`. The fact that I'm receiving the INVITE at all also means that it's either using the carriers's public ip in via or the active SIP connection session . I suspects the NAT mapping for the contact listening port gets timed out, or not supported in the first place because of NAT method. For SDP, voice receives fine without the need of ICE/STUN/TURN. There is no keep alive configuration for their SIP.

Looking into Linphone, it doesn't support UnifiedPush, even when I settle for FCM, my understanding is that I have to recompile the client in order to change the project ID so it accepts the push from my own FCM project.

For Jami, the features it supports are close enough for me to POC the above Twilio function. From the log I can see I'm receiving the push just fine however I ran into quite too many unrelated bugs for it to be feasible  (UI / TLS cert import / config flapping / actually triggering registration upon push as intended / PJ_EBUSY leaving many staled AOR in a mix of TLS and TCP).

So baresip looks the cleanest and most promising. Would you consider accepting patch if I implement something similar to https://review.jami.net/c/jami-client-android/+/22682 for baresip-studio, perhaps in a branch? One caveat is that, since Twilio SIP doesn't expose any API to retrieve the AOR so in terms of test flow or my use case, I'll have to retrieve the rfc8599 parameters manually through their console or in particular the distributor I'm testing, the local ntfy app.

**Comment by juha-h** [comment]
Regarding RFC 8599 (Push Notification with the Session Initiation Protocol (SIP)), first there should be in baresip lib possibility to add pn params to register request.  As prid, perhaps existing the uuid could be used.  Check this out and it OK, create a PR to https://github.com/baresip/baresip project that adds ;pn=yes/no and other needed other ;pn parameters to account config.

Once done, it should be quite easy to wake baresip app to send register request the same way as it is currently woken to place call.

What comes to your NAT issues, it is the task of the Registrar to keep the NAT pinhole open.  I have never experienced  any NAT problems with my Kamailio based SIP Proxy/Registrar, which can keep the pinhole open either using OPTIONS requests or TCP keepalives.  If you SIP Proxy/Registar is broken, you can always try to reduce the registration interval, which now can be configured account's settings.

**Comment by codyit** [comment]
Unfortunately their minimum registration interval is 10 minutes :)
Thanks, I'm looking into this now in my spare time, since the RFC requires it to not send those contact headers other than during REGISTER it's taking me more time than I thought (I also was never proficient in C)

One thing I needed to do for it to build was that I have to wrap the ndk ld to symlink to a ld.lld.patched:
```
#!/bin/bash
exec $(dirname -- "$(readlink -f -- "${BASH_SOURCE[0]}")")/ld.lld "${@#--no-add-needed}"
```

Won't cut an issue for it since I'm not sure if it's specific for me, perhaps it has to do with Fedora since I saw redhat in the help page so perhaps it's a redhat build specific issue.

**Comment by juha-h** [comment]
Cody T.-H. Chiu writes:

> One thing I needed to do for it to build was that I have to wrap the
> ndk ld to symlink to a ld.lld.patched: 
> ```
> #!/bin/bash
> exec $(dirname -- "$(readlink -f -- "${BASH_SOURCE[0]}")")/ld.lld "${@#--no-add-needed}"
> ```
> 
> Won't cut an issue for it since I'm not sure if it's specific for me,
> perhaps it has to do with Fedora since I saw redhat in the help page
> so perhaps it's a redhat build specific issue.

I'm using Debian and don't have such an issue.

**Comment by alex9434** [comment]
Hi @juha-h, is there an update on this? There are now multiple libraries, that makes it possible to integrate UnifiedPush and FCM into the app, e.g. 
https://codeberg.org/UnifiedPush/android-connector
https://unifiedpush.org/kdoc/foss_embedded_fcm_distributor/
https://unifiedpush.org/kdoc/embedded_fcm_distributor/
Is there any chance to integrate these for push notification. Because a lot of phones (e.g. Xiaomi, Samsung) kill apps, a push notification would be the way to reliable receive calls.

**Comment by juha-h** [comment]
Just checked and Kamailio still does not have push notification module.  What comes to Android killing baresip, it has never happened on my Samsung phones.  My current ones are A04 and A15.

**Comment by alex9434** [comment]
Hi @juha-h , I do not have a Samsung phone. I have heard that the new models do this now. Xiaomi and other brands definitively kill aggressively.
 was thinking about using FreeBPX for the push notifications. It allows you to call external scripts. Would need to develop a script that calls the UnifiedPush provider
```
[ext-did-custom]
exten => s,1,System(/usr/bin/sendpush.php "External call from ${CALLERID(num)}")
```
An alternative would be FlexiSip that has build-in push support for FCM: https://github.com/BelledonneCommunications/flexisip

**Comment by trixmoe** [comment]
I know I'm bumping an old issue, but I want to give some context on _one_ of the conditions you laid out for the Android app supporting UnifiedPush: Kamailio support

When RFC8599 support was brought up in a Kamailio issue kamailio/kamailio#3508, the issue was closed saying that "this is usually done by another service". The contributor pointed the user towards the mailing list, which has no mention of this RFC: https://lists.kamailio.org/mailman3/hyperkitty/search?mlist=sr-users%40lists.kamailio.org&q=RFC8599

I'm aware that baresip (the library) should probably have support for these things first or at the same time, but I did want to mention it.

As such, I'm not even convinced that Kamailio is interested in having RFC8599 support. It's worth noting that OpenSIPS 3.1+ does have RFC8599 support.

**Comment by juha-h** [comment]
In order to consider implementing support for UnifiedPush (= service that I don't use myself), I would need a list of things that should be added to baresip app.  For example,

- Somehow configure to account that it registers to SIP registrar only after receiving notification
- Tell to account which push distributors it accepts notifications from
- When baresip app starts, send push registration to SIP Proxy instead of SIP REGISTER request
- After receiving push notification, REGISTER once with SIP Proxy if registration is currently not active
- ...

When I wrote above, it became clear that this has nothing to do with baresip Android app.  UnifiedPush support could be added to baresip https://github.com/baresip/baresip lib and once there baresip Android app could start using it like any other baresip app (Linux CLI, GTK, WIndows, ...).

Try your luck and start discussion on page https://github.com/baresip/baresip/discussions.
