### ISSUE TITLE
Restore of baresip+ backup in baresip mysteriously fails

### ISSUE THREAD

**Issue by gdt** [juha-h/baresip-studio#226]
Observed while setting up to test for #218.   I didn't realize the test apk was baresip vs baresip+ that I had installed, and since I have that installed from f-droid with a different signature, I figured I'd have to backup and restore.   So I did backup of baresip+ and then deleted it.  I installed the test apk and restore gave me a "either password was wrong or [don't remember]".  Then I realize the app names were distinct, and re-installed baresip+ from f-droid and it restored the backup just fine.

So this is sort of 2 bug reports:
  * if the problem is that it's a plus/non-plus mismatch, say that outright
  * it seems that perhaps with warning/confirm, perhaps just doing it, cross-flavor should work
For cross-flavor:
  * nonplus to plus; all ok, except you get default video codecs
  * plus to nonplus: all ok, except the video codec config is los
 Either way, seems better than "you can't get there for here", but as always I may be missing something.

**Comment by juha-h** [comment]
baresip and baresip+ are two different apps.  you can have both of them
installed on the same device.  There is no support for backup/restore
between them.  When installing an apk of an existing app there can be
signature mismatch in which case backup should be done before proceeding
with the installation and then restore after installation.

**Comment by gdt** [comment]
I understand now that you can't backup/restore between them.   From a user viewpoint, I  see them as two build flavors of the same app, one with video support, and one with ancient android support (but maybe I have it wrong).   So it seems reasonable to expect the restore to mostly work. But certainly your call not to do that.

However, I think people may well try to do this, and an error message "Can't restore to baresip from this file because it was saved from baresip+." would be really helpful.

And, migration from baresip to baresip+ seems really helpful as when a user that has an ancient Android phone gets a new phone, they will want to migrate to baresip+, probably.

**Comment by juha-h** [comment]
Greg Troxel writes:

> I understand now that you can't backup/restore between them.   From a
> user viewpoint, I  see them as two build flavors of the same app, one
> with video support, and one with ancient android support (but maybe I
> have it wrong).   So it seems reasonable to expect the restore to
> mostly work. But certainly your call not to do that.

Their really are two different apps. baresip+ is much more complex than
baresip due to video stuff.  I personally use baresip, since I don't
like video calls.

> However, I think people may well try to do this, and an error message
> "Can't restore to baresip from this file because it was saved from
> baresip+." would be really helpful.

> And, migration from baresip to baresip+ seems really helpful as when a
> user that has an ancient Android phone gets a new phone, they will
> want to migrate to baresip+, probably.

OK, this seems like never ending story. I'll check if backup/restore
migration is currently possible or easy to make it possible.  If work
needs to be done and it is not too complex, I'll add feature request
about it to the Wiki.

I started to develop baresip in 2018 when Linphone was based on push
notifications and they didn't promise to change that:

https://github.com/BelledonneCommunications/linphone-android/issues/55

Now linphone too runs on the background, so perhaps baresip is not
needed anymore.

**Comment by gdt** [comment]
Thanks.  My main point was just to give a better error message, as I had never tried to restore before.

I can see your point about video calls, but it seems to me that once the code can be built for the phone you have, it's a simpler world to just have one app.   If they are in separate source repos, would be good to have cross pointers.   (I am only aware of one repo for both, which made me think of them as build flavors.)

As for 'not needed', I find baresip to be cleaner/simpler in a major way, and while linphone seems to work ok, your app seems to do a far better job of addressing bug reports solidly and quickly and I have more confidence in baresip.    Feel free to hit close, of course when this report is no longer useful to you.

**Comment by juha-h** [comment]
I made some tests and found out that it is not possible to use baresip to decrypt backup file that has been encrypted using baresip+ or vice versa.   The reason is that the encrypted file contains classes that are defined in the app.  So decrypting using another app does not find those classes.  For example, if the backup file has been encrypted using baresip, then encrypt using baresip+ results in error:
```
02-08 11:33:55.803 15855 15855 W Baresip+: decryptFromStream failed: java.lang.ClassNotFoundException: com.tutpro.baresip.Utils$Crypto
```
Perhaps there could be some way to share the classes between the two apps using some kind of common dependencies, but don't have resources to start exploring those possibilities.  So at present baresip and baresip+ thus are two completely separate applications.  Those users whose devices fulfill baresip+ requirements can start with that and those who later want to switch from baresip to baresip+ must start from scratch.

**Comment by juha-h** [comment]
Added feature request to Wiki. Pull requests are welcome.
