### ISSUE TITLE
Account seems to deregister / unregister itself - how to debug?

### ISSUE THREAD

**Issue by jaimet** [juha-h/baresip-studio#287]
Hi.

I'm using v48.2.0 with a sip.antisip.com account, and calling and receiving calls using g722 works fantastically. Thank you for the great sip client.

I have 1 problem. I leave the android phone powered on (it is not my main phone) and sometimes I notice (perhaps after several days of not using the phone) that the "green circle" (which indicates successful connection to the sip server?) has changed to a "white circle"(which indicates something **_other_** than a successful connection to the sip server.

I then go into the account settings, and I see that "Register" checkbox has been unchecked. I do not know if the unchecking of the "Register" checkbox is a cause or a result of the problem (or perhaps neither).

I re-check the "Register" checkbox, baresip reconnects to the sip server, and the white circle becomes green again.

I appreciate that this might be a problem with the baresip app, but perhaps it is caused by something outside of the app - perhaps a temporary problem with the sip.antisip.com sip server.

Do you know how I could debug this?

Many thanks, J

**Comment by juha-h** [comment]
If account has white dot, it means that currently the account is not registering, i.e, account's Register checkbox is not checked.  Long touch at the account in the account spinner toggles account's registration mode, i.e., green/yellow turns to white and vice versa.  The other possibility to change account's registration mode is sending a broadcast to baresip's intent receiver: https://github.com/juha-h/baresip-studio/wiki/Intent-Receiver.  Third possibility is to check/uncheck account's Register checkbox in Account activity.

These three are the only means in the code by which green account could turn white, i.e., account's checked Register checkbox becomes unchecked.  I wonder if you you have by accident long touched the account spinner, since that would be the most likely option.  Currently there is debug log message when that happens.

**Comment by jaimet** [comment]
> I wonder if you you have by accident long touched the account spinner, since that would be the most likely option.

I think that you are correct (I didn't realise that a long-press on the account spinner toggled account registration mode on and off).

I'll close this bug now and re-open if necessary. Thank you again.
