### ISSUE TITLE
Build Error

### ISSUE THREAD

**Issue by liming8964** [juha-h/baresip-studio#29]
Hello, how are you?
I am getting this error when building your source code.

```
Build command failed.
Error while executing process E:\AndroidDevTools\Sdk\cmake\3.6.4111459\bin\cmake.exe with arguments {--build F:\AndroidProjects\baresip-studio-master\app\.externalNativeBuild\cmake\debug\arm64-v8a --target baresip}

ninja: error: 'F:/AndroidProjects/baresip-studio-master/distribution/baresip/lib/arm64-v8a/libbaresip.a', needed by 'F:/AndroidProjects/baresip-studio-master/app/build/intermediates/cmake/debug/obj/arm64-v8a/libbaresip.so', missing and no known rule to make it
```

Looking forward to your favorable reply.

Android Studio 3.4
Build #AI-183.5429.30.34.5452501, built on April 10, 2019
JRE: 1.8.0_152-release-1343-b01 amd64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Windows 10 10.0

**Comment by juha-h** [comment]
Dev-Lee writes:

```
> Build command failed.
> Error while executing process E:\AndroidDevTools\Sdk\cmake\3.6.4111459\bin\cmake.exe with arguments {--build F:\AndroidProjects\baresip-studio-master\app\.externalNativeBuild\cmake\debug\arm64-v8a --target baresip}
> 
> ninja: error: 'F:/AndroidProjects/baresip-studio-master/distribution/baresip/lib/arm64-v8a/libbaresip.a', needed by 'F:/AndroidProjects/baresip-studio-master/app/build/intermediates/cmake/debug/obj/arm64-v8a/libbaresip.so', missing and no known rule to make it
```

Make sure that you have built the libs as described in README.md.

**Comment by liming8964** [comment]
Sure. Already did many times.

**Comment by juha-h** [comment]
The error message tells that libbaresip.a is not found in the lib where your build system expects to find it. Perhaps your CMAKE_SOURCE_DIR points to wrong place.

Looks like you are trying to do the build on windows (which I don't know anything about). Switch to Linux and build works as it.  Otherwise you have to figure out yourself what needs to be changed.

**Comment by liming8964** [comment]
Linux?
I am running the Android Studio 3.4 on Windows 10.
Sorry i have no much experience in Android Studio on Linux.

**Comment by juha-h** [comment]
Dev-Lee writes:

> I am running the Android Studio 3.4 on Windows 10.
> Sorry i have no much experience in Android Studio on Linux.

As I mentioned, looks like in your environment, the paths don't match.
Find out which dir libbaresip.a is located and set distribution_DIR in
CMakeLists.txt accordingly.

**Comment by liming8964** [comment]
Other apps are running successfully.
Only this app has an issue when building.

**Comment by juha-h** [comment]
Dev-Lee writes:

> Other apps are running successfully.
> Only this app has an issue when building.

You need to find out yourself where the libs are in your environment and
fix things. I don't know (and don't want to know) anything about
Windows.

I'll add a note to README.md that only Linux related build issues will
be dealt with, since that is the only environment I have myself.

**Comment by juha-h** [comment]
The error message clearly states that libbaresip.a is not found in the location where is should be after installation of the libs.  I'll close this, since there is no way baresip app could be built without it.
