### ISSUE TITLE
clarification:"does not depend on third party push notification services"

### ISSUE THREAD

**Issue by bagherfathi** [juha-h/baresip-studio#325]
Hi everyone,
as you know android for saving battery goes to sleep, and apps like sip that need to send regular REGISTER message has high battery usage it's possible for android automatically or asks the user to put the sip app to sleep.
to solve this problem, SIP proxies block the INVITE message for example 3 seconds and send a push notification to the android client to wake up the client and after the client sends the REGISTER message to the SIP proxy, the proxy unblocks the blocked INVITE and session initiation continues.
as I saw in your comments in the google play store and f-droid you mentioned that your tools: "does not depend on third party push notification services."
What's the meaning of the above phrase?
now:

Do you force your client to be awake always and battery usage is not mattered to you?
Do you have a built-in push notification in baresip to support internally?
or any other trade-offed solution
thanks

**Comment by juha-h** [comment]
There is no push notification support in this app. 

I used to use Linphone but at some point it started to require use of Google's push notification service, which I didn't like. See this thread https://github.com/BelledonneCommunications/linphone-android/issues/55 and my comment on it.  So that motivated me to start building this app as replacement to Linphone.  May be also now Linphone stays awake without push notifications when they realized that some people don't like Google to know when they get messages or calls.

So, the answer is, there is and will not be push notification support in this app.  You need to choose some other app if you think that this app consumes to much battery.  You can also read Wiki page https://github.com/juha-h/baresip-studio/wiki/Battery-Consumption.

**Comment by bagherfathi** [comment]
thanks @juha-h

**Comment by gdt** [comment]
I think it would be nice if this supported Unified Push at some point.  That's coding work, but doesn't have the privacy brokenness of google push.
