### ISSUE TITLE
Diverter URI in baresip

### ISSUE THREAD

**Issue by AviWA** [juha-h/baresip-studio#360]
sip:919017362726@192.168.29.101  is the diverter uri i want to display this in baresip activity screen when call comes in.

This is the TRACE of INVITE REQUEST 

https://user-images.githubusercontent.com/123717548/233438125-37e67c78-7bb6-4b99-a423-5f0398d1df25.PNG

Please reply I can't understand what you said at that time so it took time.

**Comment by juha-h** [comment]
`sip:919017362726@192.168.29.101` is To and Request URI telling who is the receiver, not the diverter of the request.  Diverter URI is found in Diversion or History-Info header and your INVITE request does not have either.  Please fix your SIP proxy or SBC that forwarded the request to baresip so that it adds one of those headers.
