### ISSUE TITLE
Favourite contacts? 

### ISSUE THREAD

**Issue by bjlockie** [juha-h/baresip-studio#417]
Does baresip have access to the contacts I marked as favourites?
That would be nice to have.

**Comment by juha-h** [comment]
Currently baresip contacts does not have possibility to mark a contact with a favorite star.  I want to keep baresip simple and don't want to make baresip app also a contact app, since there are many already around.

So have you selected in Settings to use Android contacts and want to see favorite ones on the top of the list or something else?

**Comment by bjlockie** [comment]
> So have you selected in Settings to use Android contacts and want to see favorite ones on the top of the list or something else?

Exactly.
Favourites are not stored with the Android contact?

**Comment by juha-h** [comment]
Commit https://github.com/juha-h/baresip-studio/commit/28da3c8fa1007964398f2b14b6fc8dba932946c8 show starred (favorite) Android contacts on top of contacts list.

**Comment by juha-h** [comment]
This feature should now be available in baresip 59.1.0 and  baresip+ 46.2.0.

**Comment by bjlockie** [comment]
Great to hear

**Comment by arichiardi** [comment]
Great! Was waiting for this feature! Thank you very much for it.
