### ISSUE TITLE
Device's microphone is losing focus after disconnecting headset with mic

### ISSUE THREAD

**Issue by carman247** [juha-h/baresip-studio#449]
If I connect a headset with a microphone during a call, and then disconnect it, the devices microphone no longer seems to be in focus/enabled, and the person on the other side of the call can no longer hear me. I can hear them fine out of the speakers, and if I reconnect the headset they can hear me again.

Do you have any idea why this is happening and how to rectify it?

**Comment by juha-h** [comment]
carman247 writes:

> If I connect a headset with a microphone during a call, and then
> disconnect it, the devices microphone no longer seems to be in
> focus/enabled, and the person on the other side of the call can no
> longer hear me. I can hear them fine out of the speakers, and if I
> reconnect the headset they can hear me again.

I tried by making call w/o headset.  Then I connected headset and both
its speaker and mic worked fine.  Then I disconnected the headset and
device's mic and speaker worked fine again.  I know that the mic worked
because I was able to record a new greeting to my voicemail app.  Then I
repeated the same test again and everything worked OK.

So I can't reproduce this issue.  Perhaps something to do with your
device/os.  See also Wiki about Reporting Issues.

**Comment by carman247** [comment]
Hi, thanks for the reply. I've just tested on another device (Mi 9T Pro - Android 11)  and it seems to work like you have reported. 

Must be something device specific with my Samsung Tab A8 (Android 13).

I'll close this issue but can report back if I find a solution.
