### ISSUE TITLE
Baresip opens too big

### ISSUE THREAD

**Issue by DDQW** [juha-h/baresip-studio#513]
Yes i know the title sound stupid but that is whats happening.

Baresip for some reason opens so fullscreen that the top bar is displayed under the android statusbar and therefore not usable

i am using:
Pixel 8 Pro
Graphene OS (android 15) Build 2024112700
baresip+ from 5 days ago and baresip from 9 days ago have been tested

**Comment by juha-h** [comment]
@DDQW Sorry, but I cannot reproduce this on my Samsung device nor Pixel 7 API 34 emulator: 

![Screenshot_20241205_011445](https://github.com/user-attachments/assets/5837f121-d4a1-454d-99f8-36a930bfa3ad)

Since which version of baresip did this issue start?  I don't remember making recently any changes that would affect the main screen layout.

**Comment by DDQW** [comment]
i just instalked today cause i want to replace easybells atrocious app with baresip. i sadly cannot say which Version exactly

![Screenshot_20241205-011952](https://github.com/user-attachments/assets/c254432d-8183-4345-b46e-b608aea10d99)
![Screenshot_20241205-011937](https://github.com/user-attachments/assets/07670824-52cd-48bb-89d8-aef32987140b)

here two Screenshot from baresip and baresip+

are you running graphene in the pixel7 Emulator?

**Comment by juha-h** [comment]
I was able to reproduce the issue using Pixel Pro 8 API 35.  So something has changed from API 34 to 35.  Android is a never ending moving target.

**Comment by DDQW** [comment]
purrfect

i eagerly await the next update then.

Have a good day

**Comment by juha-h** [comment]
@DDQW I created new baresip version 62.1.0 that should solve the issue.  It is available here: https://github.com/juha-h/baresip-studio/releases and after about a week in F-Droid.  If you try from GitHub, backup before install.

The fix is temporary, since it will take many days to properly change to code for Android 15 compatibility.  Very bad move from Google.

**Comment by FloatingLizard** [comment]
Same here on Graphene os pixel 8 pro.

**Comment by juha-h** [comment]
@FloatingLizard WIth what version of baresip?

**Comment by juha-h** [comment]
@DDQW baresip version 62.1.0 is now available at F-Droid. Please give it a try.

**Comment by DDQW** [comment]
opens correctly
